name: "Podcast Generator-AK"
author: "Aryaman Kaushik"
description: "Generate a feed for a podacst from a  yaml file"
runs:
  using: "docker"
  image: "chevron-right"
branding:
  icons: "activity"
  color: "red"
inputs:
  email:
    description: The committer's email adddress
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor}}
